version: "3.9"
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  api:
    build: .
    environment:
      - MONGODB_URI=mongodb://mongo:27017/quiz_engine_api
      - JWT_SECRET=supersecret_change_me
      - PORT=4000
    depends_on:
      - mongo
    ports:
      - "4000:4000"
volumes:
  mongo_data: {}
